using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Policy;
using System.Text;
using Reinforced.Typings.Exceptions;
using Reinforced.Typings.Visitors;
using Reinforced.Typings.Visitors.TypeScript;
using Reinforced.Typings.Visitors.Typings;

namespace Reinforced.Typings
{
    internal class FilesOperations : IFilesOperations
    {
        private readonly ExportContext _context;
        private readonly List<string> _tmpFiles = new List<string>();

        public FilesOperations(ExportContext context)
        {
            _context = context;
        }

        public void DeployTempFiles()
        {
            foreach (var tmpFile in _tmpFiles)
            {
                var origFile = Path.GetFileNameWithoutExtension(tmpFile);
                var origDir = Path.GetDirectoryName(tmpFile);
                origFile = Path.Combine(origDir, origFile);
                try
                {
                    if (File.Exists(origFile)) File.Delete(origFile);
                    File.Move(tmpFile, origFile);
#if DEBUG
                    Console.WriteLine("File replaced: {0} -> {1}", tmpFile, origFile);
#endif
                }
                catch (Exception ex)
                {
                    ErrorMessages.RTE0002_DeployingFilesError.Throw(origFile, ex.Message);
                }
            }
        }

        public void Export(string fileName, ExportedFile file)
        {

            using (var fs = GetTmpFile(fileName))
            {
                using (var tw = new StreamWriter(fs))
                {
                    var visitor = _context.ExportPureTypings ? new TypingsExportVisitor(tw) : new TypeScriptExportVisitor(tw);
                    WriteWarning(tw);
                    foreach (var fileGlobalReference in file.GlobalReferences.References)
                    {
                        visitor.Visit(fileGlobalReference);
                    }

                    foreach (var referencesReference in file.References.References)
                    {
                        visitor.Visit(referencesReference);
                    }

                    foreach (var globalReferencesImport in file.GlobalReferences.Imports)
                    {
                        visitor.Visit(globalReferencesImport);
                    }

                    foreach (var referencesImport in file.References.Imports)
                    {
                        visitor.Visit(referencesImport);
                    }

                    foreach (var fileNamespace in file.Namespaces)
                    {
                        visitor.Visit(fileNamespace);
                    }
                }
            }
        }

        private void ExportReferences(InspectedReferences refs, VisitorBase visitor)
        {
            foreach (var refsReference in refs.References)
            {

            }
        }

        private void WriteWarning(TextWriter tw)
        {
            if (_context.WriteWarningComment)
            {
                tw.WriteLine("//     This code was generated by a Reinforced.Typings tool. ");
                tw.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
                tw.WriteLine("//     the code is regenerated.");
                tw.WriteLine();
            }
        }

        public Stream GetTmpFile(string fileName)
        {
            fileName = fileName + ".tmp";
            try
            {
                var dir = Path.GetDirectoryName(fileName);
                if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

                if (File.Exists(fileName))
                {
                    File.Delete(fileName);
                }
#if DEBUG
                Console.WriteLine("Temp file aquired: {0}", fileName);
#endif
                _tmpFiles.Add(fileName);
            }
            catch (Exception ex)
            {
                ErrorMessages.RTE0001_TempFileError.Throw(fileName, ex.Message);
            }

            return File.OpenWrite(fileName);
        }



        public void ClearTempRegistry()
        {
            _tmpFiles.Clear();
        }
    }

    internal static class ArrayExtensions
    {
        public static T I<T>(this T[] array, int idx)
        {
            if (idx >= array.Length) return default(T);
            return array[idx];
        }
    }
}