//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
var Reinforced;
(function (Reinforced) {
    var Typings;
    (function (Typings) {
        var Samples;
        (function (Samples) {
            var Difficult;
            (function (Difficult) {
                var CodeGenerators;
                (function (CodeGenerators) {
                    var Controllers;
                    (function (Controllers) {
                        var JQueryController = (function () {
                            function JQueryController() {
                            }
                            JQueryController.SimpleIntControllerMethod = function (loadingPlaceholderSelector, disableElement) {
                                if (loadingPlaceholderSelector === void 0) { loadingPlaceholderSelector = ''; }
                                if (disableElement === void 0) { disableElement = ''; }
                                return QueryController.query('/JQuery/SimpleIntControllerMethod', {}, loadingPlaceholderSelector, disableElement);
                            };
                            JQueryController.ControllerMethodWithParameters = function (number, s, boolValue, loadingPlaceholderSelector, disableElement) {
                                if (loadingPlaceholderSelector === void 0) { loadingPlaceholderSelector = ''; }
                                if (disableElement === void 0) { disableElement = ''; }
                                return QueryController.query('/JQuery/ControllerMethodWithParameters', { 'number': number, 's': s, 'boolValue': boolValue }, loadingPlaceholderSelector, disableElement);
                            };
                            JQueryController.ControllerReturningObject = function (loadingPlaceholderSelector, disableElement) {
                                if (loadingPlaceholderSelector === void 0) { loadingPlaceholderSelector = ''; }
                                if (disableElement === void 0) { disableElement = ''; }
                                return QueryController.query('/JQuery/ControllerReturningObject', {}, loadingPlaceholderSelector, disableElement);
                            };
                            JQueryController.ControllerReturningObjectWithParameters = function (echo, loadingPlaceholderSelector, disableElement) {
                                if (loadingPlaceholderSelector === void 0) { loadingPlaceholderSelector = ''; }
                                if (disableElement === void 0) { disableElement = ''; }
                                return QueryController.query('/JQuery/ControllerReturningObjectWithParameters', { 'echo': echo }, loadingPlaceholderSelector, disableElement);
                            };
                            return JQueryController;
                        })();
                        Controllers.JQueryController = JQueryController;
                    })(Controllers = CodeGenerators.Controllers || (CodeGenerators.Controllers = {}));
                })(CodeGenerators = Difficult.CodeGenerators || (Difficult.CodeGenerators = {}));
            })(Difficult = Samples.Difficult || (Samples.Difficult = {}));
        })(Samples = Typings.Samples || (Typings.Samples = {}));
    })(Typings = Reinforced.Typings || (Reinforced.Typings = {}));
})(Reinforced || (Reinforced = {}));
//# sourceMappingURL=project.js.map