//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
var Reinforced;
(function (Reinforced) {
    var Typings;
    (function (Typings) {
        var Samples;
        (function (Samples) {
            var Simple;
            (function (Simple) {
                var Quickstart;
                (function (Quickstart) {
                    var Models;
                    (function (Models) {
                        var User = (function () {
                            function User() {
                            }
                            return User;
                        })();
                        Models.User = User;
                        (function (UserType) {
                            UserType[UserType["One"] = 0] = "One";
                            UserType[UserType["Two"] = 1] = "Two";
                        })(Models.UserType || (Models.UserType = {}));
                        var UserType = Models.UserType;
                    })(Models = Quickstart.Models || (Quickstart.Models = {}));
                })(Quickstart = Simple.Quickstart || (Simple.Quickstart = {}));
            })(Simple = Samples.Simple || (Samples.Simple = {}));
        })(Samples = Typings.Samples || (Typings.Samples = {}));
    })(Typings = Reinforced.Typings || (Reinforced.Typings = {}));
})(Reinforced || (Reinforced = {}));
//# sourceMappingURL=Server.js.map