//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.


module Reinforced.Typings.Samples.Difficult.CodeGenerators.Controllers {
	export class JQueryController
	{
		/** Wrapper method for call SimpleIntMethod of JQueryController */
		public static SimpleIntMethod(loadingPlaceholderSelector: string = '', disableElement: string = '') : JQueryPromise<number>
		{
			return QueryController.query<number>(
			        '/JQuery/SimpleIntMethod', 
			        {  }, 
			        loadingPlaceholderSelector,
			        disableElement
			    );
		}
		/** Wrapper method for call MethodWithParameters of JQueryController */
		public static MethodWithParameters(num: number, s: string, boolValue: boolean, loadingPlaceholderSelector: string = '', disableElement: string = '') : JQueryPromise<string>
		{
			return QueryController.query<string>(
			        '/JQuery/MethodWithParameters', 
			        { 'num': num, 's': s, 'boolValue': boolValue }, 
			        loadingPlaceholderSelector,
			        disableElement
			    );
		}
		/** Wrapper method for call ReturningObject of JQueryController */
		public static ReturningObject(loadingPlaceholderSelector: string = '', disableElement: string = '') : JQueryPromise<Reinforced.Typings.Samples.Difficult.CodeGenerators.Models.IJQuerySampleResponseModel>
		{
			return QueryController.query<Reinforced.Typings.Samples.Difficult.CodeGenerators.Models.IJQuerySampleResponseModel>(
			        '/JQuery/ReturningObject', 
			        {  }, 
			        loadingPlaceholderSelector,
			        disableElement
			    );
		}
		/** Wrapper method for call ReturningObjectWithParameters of JQueryController */
		public static ReturningObjectWithParameters(echo: string, loadingPlaceholderSelector: string = '', disableElement: string = '') : JQueryPromise<Reinforced.Typings.Samples.Difficult.CodeGenerators.Models.IJQuerySampleResponseModel>
		{
			return QueryController.query<Reinforced.Typings.Samples.Difficult.CodeGenerators.Models.IJQuerySampleResponseModel>(
			        '/JQuery/ReturningObjectWithParameters', 
			        { 'echo': echo }, 
			        loadingPlaceholderSelector,
			        disableElement
			    );
		}
		/** Wrapper method for call VoidMethodWithParameters of JQueryController */
		public static VoidMethodWithParameters(model: Reinforced.Typings.Samples.Difficult.CodeGenerators.Models.IJQuerySampleResponseModel, loadingPlaceholderSelector: string = '', disableElement: string = '') : JQueryPromise<any>
		{
			return QueryController.query<any>(
			        '/JQuery/VoidMethodWithParameters', 
			        { 'model': model }, 
			        loadingPlaceholderSelector,
			        disableElement
			    );
		}
	}
}
module Reinforced.Typings.Samples.Difficult.CodeGenerators.Models {
	export interface IJQuerySampleResponseModel
	{
		Message: string;
		Success: boolean;
		CurrentTime: string;
	}
}
